version: '3'

volumes:
  db-data: 
services:
  front:
    build: 
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - './front/:/usr/src/app'
    ports:
      - '8001:3000'
    tty: true
    stdin_open: true
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./api/:/spot-locator-api
    depends_on:
      - db
    links:
      - db
    stdin_open: true
    tty: true
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql

  
